//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int A_Id { get; set; }
        public int U_Id { get; set; }
        public int C_Id { get; set; }
        public int T_Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public System.DateTime Due_Date { get; set; }
        public int TTC { get; set; }
        public string Description { get; set; }
        public decimal Completion { get; set; }
    
        public virtual Asgmt_Type Asgmt_Type { get; set; }
        public virtual Class Class { get; set; }
        public virtual User User { get; set; }
    }
}
